version: '3'

tasks:
  # Update this repo with the copier-template
  # `--vcs-ref HEAD` to avoid `You are downgrading from 0.1.0.post2.dev0+0a9a33e to 0.1.0. Downgrades are not supported.`
  update:
    cmds:
      - |
        copier update --vcs-ref HEAD .
  transcribe:
    cmds:
      - |
        uv run src\gerardnico\transcribe\cli.py
  test:
    cmds:
      -|
      # verbose: uv run pytest -v
      uv run pytest
  mcp-inspect:
    cmds:
      - |
        uv run fastmcp inspect src\gerardnico\transcribe\cli.py mcp
  cert:
    cmds:
      - |
        openssl req -x509 -newkey rsa:4096 -keyout private.key -out certificate.crt -days 365 -nodes -subj '/CN=localhost'
