version: '3'

tasks:
  # Update this repo with the copier-template
  # `--vcs-ref HEAD` to avoid `You are downgrading from 0.1.0.post2.dev0+0a9a33e to 0.1.0. Downgrades are not supported.`
  update:
    cmds:
      - |
        copier update --vcs-ref HEAD .
  install:
    cmds:
      - |
        pipx install -e --force .
  transcribe:
    # works also on Windows as gotask uses its own sh engine
    # call it with: task transcribe -- {ARGS}
    cmds:
      - |
        export OAUTH_CLIENT_ID=$(pass transcribe/google/oauth-client-id)
        export OAUTH_CLIENT_SECRET=$(pass transcribe/google/oauth-client-secret)
        uv run -m gerardnico.transcribe.cli {{.CLI_ARGS}}
  test:
    cmds:
      - |
        # verbose: uv run pytest -v
        uv run pytest
