version: '3'

tasks:
  # Update this repo with the copier-template
  # `--vcs-ref HEAD` to avoid `You are downgrading from 0.1.0.post2.dev0+0a9a33e to 0.1.0. Downgrades are not supported.`
  update:
    cmds:
      - |
        copier update --vcs-ref HEAD .
  start:
    cmds:
      - |
        uv run mcp dev src\gerardnico\transcribe\mcp\mcp_server.py
  cert:
    cmds:
      - |
        openssl req -x509 -newkey rsa:4096 -keyout private.key -out certificate.crt -days 365 -nodes -subj '/CN=localhost'
